### DISCUSSION TITLE
waline 的背景图怎么更改

### DISCUSSION THREAD

**Discussion by fez7yoe** [walinejs/waline#1210] [Q&A] [answered]
在 <code>bg:</code> ( <code>serverURL:</code> 我有填上请放心)
```
waline:
  serverURL: # Waline server address url
  bg: # waline background
  pageview: false
  option:
```
试了三种方法，仍然读取不到背景图
```
1. /img/xxx.png
2. https://xxx.png)
3. url(https://xxx.png)
```
没头绪了 -w-
