### DISCUSSION TITLE
css 和 mjs 配置CDN || css and mjs configure CDN

### DISCUSSION THREAD

**Discussion by tangluya** [walinejs/waline#1987] [Q&A] [answered]
### Describe the bug | 问题描述

我目前用的umpkg
```
waline:
      enable: true
      url: 
        css: https://unpkg.com/@waline/client@v2/dist/waline.css
        js: https://unpkg.com/@waline/client@v2/dist/waline.mjs
```
我想换为国内的cdn，比如七牛的 https://www.staticfile.org
但是他们的是
https://cdn.staticfile.org/waline/2.15.5/waline.css
https://cdn.staticfile.org/waline/2.15.5/waline.js
2.15.5 版本

我不太懂这两个有什么区别，请问可以直接用替换吗

### Website URL | 问题网站

blog.tanglu.me

### Where your waline deploy? | 服务部署在哪里？

Vercel (Default)

### Where your comment data store? | 数据存储在哪里？

LeanCloud(https://leancloud.app)

---
### Describe the bug | Problem description

I am currently using umpkg
```
Waline:
      enable: true
      url:
        css: https://unpkg.com/@waline/client@v2/dist/waline.css
        js: https://unpkg.com/@waline/client@v2/dist/waline.mjs
```
I want to switch to a domestic CDN, such as Qiniu's https://www.staticfile.org
but theirs is
https://cdn.staticfile.org/waline/2.15.5/waline.css
https://cdn.staticfile.org/waline/2.15.5/waline.js
Version 2.15.5

I don't quite understand the difference between these two, can I replace them directly?

### Website URL | Problem Website

blog.tanglu.me

### Where your waline deploy? | Where is the service deployed?

Vercel (Default)

### Where your comment data store? | Where is your comment data store?

LeanCloud(https://leancloud.app)
