### DISCUSSION TITLE
Q: 无法登录/注册管理后台 || Q: Unable to log in/register the management backend

### DISCUSSION THREAD

**Discussion by alomerry** [walinejs/waline#2126] [Q&A]
### Describe the bug | 问题描述

![image](https://github.com/walinejs/waline/assets/34118544/6d4fa291-7f8e-41d8-824c-69f84a121920)

无法登录/注册管理后台，首个管理员账号我是在本地 ip 访问的情况下注册成功的。根据截图看起来是访问了 http 的 domain

- 部署方式：独立部署（k8s Pod）+ frp 内网穿透

<details>
<summary> 环境变量 </summary>

```yml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: waline-deployment
  namespace: alomerry
spec:
  replicas: 1
  selector:
    matchLabels:
      app: waline
  template:
    metadata:
      labels:
        app: waline
    spec:
      containers:
      - image: lizheming/waline:1.31.7-alpine
        name: waline
        env:
        - name: TZ
          value: "Asia/Shanghai"
        - name: SITE_URL
          value: "https://waline.alomerry.com"
        - name: MYSQL_HOST
          value: "mysql-service"
        - name: MYSQL_PORT
          value: "3306"
        - name: MYSQL_DB
          value: "waline"
        - name: MYSQL_USER
          value: "waline"
        - name: MYSQL_PASSWORD
          value: "xxx"
        - name: AUTHOR_EMAIL
          value: "alomerry.wu@gmail.com"
        - name: SECURE_DOMAINS
          value: "blog.alomerry.com,waline.alomerry.com"
        - name: WEBHOOK
          value: "xxx"
        ports:
        - containerPort: 8360
          name: waline-port
```
</details>

<details>

<summary>Nginx 配置</summary>

```nginx
server
{
    listen 443 ssl http2;
    server_name waline.alomerry.com;
    root /root/apps/nginx/site/waline.alomerry.com;

    ssl_certificate    /root/apps/nginx/cert/waline.alomerry.com/fullchain.pem;
    ssl_certificate_key    /root/apps/nginx/cert/waline.alomerry.com/privkey.pem;
    ssl_protocols TLSv1.1 TLSv1.2 TLSv1.3;
    ssl_ciphers EECDH+CHACHA20:EECDH+CHACHA20-draft:EECDH+AES128:RSA+AES128:EECDH+AES256:RSA+AES256:EECDH+3DES:RSA+3DES:!MD5;
    ssl_prefer_server_ciphers on;
    ssl_session_cache shared:SSL:10m;
    ssl_session_timeout 10m;
    error_page 497  https://$host$request_uri;

    location / {
        proxy_pass         http://127.0.0.1:7951;

        proxy_set_header Upgrade           $http_upgrade;
        proxy_set_header Connection        $connection_upgrade;

        proxy_set_header Host              $host;
        proxy_set_header X-Real-IP         $remote_addr;
        proxy_set_header X-Forwarded-For   $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto http;
        proxy_set_header X-Forwarded-Host  $host;
        proxy_set_header X-Forwarded-Port  $server_port;
    }
    
    access_log  /root/apps/nginx/logs/waline.alomerry.com.log;
    error_log   /root/apps/nginx/logs/waline.alomerry.com.error.log;
}
```

</details>

### Website URL | 问题网站

https://waline.alomerry.com

### Where your waline deploy? | 服务部署在哪里？

Self Host

### Where your comment data store? | 数据存储在哪里？

MySQL

---
### Describe the bug | Problem description

![image](https://github.com/walinejs/waline/assets/34118544/6d4fa291-7f8e-41d8-824c-69f84a121920)

Unable to log in/register the management backend. I successfully registered the first administrator account with local IP access. According to the screenshot, it seems that the domain of http is accessed.

- Deployment method: independent deployment (k8s Pod) + frp intranet penetration

<details>
<summary> Environment variables </summary>

```yml
apiVersion: apps/v1
Kind: Deployment
metadata:
  name:waline-deployment
  namespace: alomerry
spec:
  replicas: 1
  selector:
    matchLabels:
      app:waline
  template:
    metadata:
      labels:
        app:waline
    spec:
      containers:
      - image: lizheming/waline:1.31.7-alpine
        name:waline
        env:
        - name: TZ
          value: "Asia/Shanghai"
        - name: SITE_URL
          value: "https://waline.alomerry.com"
        - name: MYSQL_HOST
          value: "mysql-service"
        - name: MYSQL_PORT
          value: "3306"
        - name: MYSQL_DB
          value: "waline"
        - name: MYSQL_USER
          value: "waline"
        - name: MYSQL_PASSWORD
          value: "xxx"
        - name: AUTHOR_EMAIL
          value: "alomerry.wu@gmail.com"
        - name: SECURE_DOMAINS
          value: "blog.alomerry.com,waline.alomerry.com"
        - name: WEBHOOK
          value: "xxx"
        ports:
        - containerPort: 8360
          name:waline-port
```
</details>

<details>

<summary>Nginx configuration</summary>

```nginx
server
{
    listen 443 ssl http2;
    server_name waline.alomerry.com;
    root /root/apps/nginx/site/waline.alomerry.com;

    ssl_certificate /root/apps/nginx/cert/waline.alomerry.com/fullchain.pem;
    ssl_certificate_key /root/apps/nginx/cert/waline.alomerry.com/privkey.pem;
    ssl_protocols TLSv1.1 TLSv1.2 TLSv1.3;
    ssl_ciphers EECDH+CHACHA20:EECDH+CHACHA20-draft:EECDH+AES128:RSA+AES128:EECDH+AES256:RSA+AES256:EECDH+3DES:RSA+3DES:!MD5;
    ssl_prefer_server_ciphers on;
    ssl_session_cache shared:SSL:10m;
    ssl_session_timeout 10m;
    error_page 497 https://$host$request_uri;

    location/{
        proxy_pass http://127.0.0.1:7951;

        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection $connection_upgrade;

        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto http;
        proxy_set_header X-Forwarded-Host $host;
        proxy_set_header X-Forwarded-Port $server_port;
    }
    
    access_log /root/apps/nginx/logs/waline.alomerry.com.log;
    error_log /root/apps/nginx/logs/waline.alomerry.com.error.log;
}
```

</details>

### Website URL | Problem website

https://waline.alomerry.com

### Where your waline deploy? | Where is the service deployed?

Self Host

### Where your comment data store? | Where is the data stored?

MySQL
