### DISCUSSION TITLE
Some suggestions

### DISCUSSION THREAD

**Discussion by Mister-Hope** [walinejs/waline#223] [Q&A] [answered]
1. Add algolia search. 

    Just apply it [here](https://docsearch.algolia.com/apply/) The default search box only index headings.

2. Darkmode support is a cool feature, but it is not documented.😪(Could you check if you miss document other features as well?)

3. Setting class to body may cause side effects. So I suggest setting the dark theme with `waline-dark` attribute by default. So it will have no side effects.. Also mathml sould have similar change too

    At meantime, add a option called `autoDark` in `@waline/client`. Inject these below only when it's set to `true`.

    ![image](https://user-images.githubusercontent.com/33315834/116552888-20dde400-a92c-11eb-8e4d-9a4706faaa70.png)

4. Only few visitors on web have their own websites. So I think changing the `meta` default from `['nick', 'mail', 'link']` to `['nick', 'mail']` would be better (It's also something I want to report to valine). Some of the users do confuse about it when they see the comment box for the first time.

5. I would like to rewrite the style system using [css variables](https://developer.mozilla.org/en-US/docs/Web/CSS/var()) to make it more configuable.
   > like this, but all with `waline-` prefix
   ![image](https://user-images.githubusercontent.com/33315834/116554246-8d0d1780-a92d-11eb-88da-fc5b36e9724b.png)

    If you think it's ok, are you familiar with sass? I realy want to rewrite with a css framework. (I saw your profile, you said you are a frontend developer) Nesting the selectors would be much more better to read than this:

    ```css
    @media screen and (max-width: 720px) {
      .v[data-class='v'] .vcards .vcard .vimg {
        width: 2.5em;
        height: 2.5em;
      }
    }

    .v[data-class='v'] .vcards .vcard .vhead {
      line-height: 1.5;
      margin-top: 0;
    }

    .v[data-class='v'] .vcards .vcard .vhead .vnick {
      position: relative;
      font-size: 0.875em;
      font-weight: 500;
      margin-right: 0.875em;
      cursor: pointer;
      text-decoration: none;
      display: inline-block;
    }

    .v[data-class='v'] .vcards .vcard .vhead .vnick:hover {
      color: #d7191a;
    }

    .v[data-class='v'] .vcards .vcard .vhead .vmark {
      font-size: 0.775em;
      margin-right: 0.875em;
      cursor: pointer;
      text-decoration: none;
      display: inline-block;
      background: #2196f3;
      border-radius: 3px;
      color: #fff;
      padding: 0 0.3em;
    }
    ````
