### DISCUSSION TITLE
在hexo主题配置文件中配置了locale选项但是在博客中无法展示效果

### DISCUSSION THREAD

**Discussion by zengchen233** [walinejs/waline#730] [Q&A] [answered]
![image](https://user-images.githubusercontent.com/67224979/147384093-45dcbd39-9e7e-4881-a8aa-48e527eba0da.png)

在博客中无法展示：https://zengchen233.cn/posts/54b83927/

**Comment by lizheming** [comment, marked as answer]
把 `-` 都去掉
```yaml
locale:
  placeholder: 'xxx'
  admin: 'xxx'
```
