### ISSUE TITLE
[Bug]: 评论无法显示，前端显示刷新

### ISSUE THREAD

**Issue by cyicz123** [walinejs/waline#1108]
### 问题描述 | Describe the bug

评论无法显示了。出现刷新按钮，但是按了没反应。
**控制台显示错误如下**
![image](https://user-images.githubusercontent.com/44216455/172405609-b4ce828f-ea33-4c6d-acd3-4202f1b08f25.png)
后台是有输出的，显示有mysql操作日志
```
[2022-06-07T22:22:22.564] [14] [INFO] - SQL: SELECT `id`,`email`,`url`,`display_name`,`type`,`github`,`twitter`,`facebook`,`google`,`weibo`,`qq`,`avatar`,`2fa`,`label`,`id` FROM `wl_Users` WHERE ( `email` = 'cyicz123@outlook.com' ), Time: 1ms
```
评论可以插入，并且有显示。但是只要一刷新网页，评论就会消失。

### 问题网站 | Website URL

https://comments.cyicz123.top

### 服务部署在哪里？ | Where your waline deploy?

Other

### 数据存储在哪里？| Where your comment data store?

MySQL

**Comment by lizheming** [comment]
是不是独立部署的，有 Nginx 代理之类的，看下有没有把请求参数代理过去，提供下 conf 配置文件吧

**Comment by cyicz123** [comment]
你好，这是我的nginx配置，是通过nginx proxy manager网页端ui自动配置的。
``` nginx
server {
  set $forward_scheme http;
  set $server         "172.17.0.1";
  set $port           8360;
  listen 80;
  listen [::]:80;
  listen 443 ssl http2;
  listen [::]:443 ssl http2;
  server_name comments.cyicz123.top;
  # Let's Encrypt SSL
  include conf.d/include/letsencrypt-acme-challenge.conf;
  include conf.d/include/ssl-ciphers.conf;
  ssl_certificate /etc/letsencrypt/live/npm-2/fullchain.pem;
  ssl_certificate_key /etc/letsencrypt/live/npm-2/privkey.pem;
  # Block Exploits
  include conf.d/include/block-exploits.conf;
  # Force SSL
  include conf.d/include/-;
  access_log /data/logs/proxy-host-12_access.log proxy;
  error_log /data/logs/proxy-host-12_error.log warn;
  location / {
    add_header       X-Served-By $host;
    proxy_set_header Host $host;
    proxy_set_header X-Forwarded-Scheme $scheme;
    proxy_set_header X-Forwarded-Proto  $scheme;
    proxy_set_header X-Forwarded-Host   $host;
    proxy_set_header X-Forwarded-Port   $port;
    proxy_set_header X-Forwarded-For    $remote_addr;
    proxy_set_header X-Real-IP          $remote_addr;
    proxy_pass $forward_scheme://$server:$port$request_uri;
  }
  # Custom
  include /data/nginx/custom/server_proxy[.]conf;
}

```
我用的是docker-compose部署，以下是我的docker-compose配置
``` yaml
version: '3'

services:
  waline:
    container_name: waline
    image: lizheming/waline:latest
    restart: always
    ports:
      - 8360:8360
    volumes:
      - ./data:/app/data
    environment:
      - TZ=Asia/Shanghai
      - MYSQL_HOST=XXXXXXX
      - MYSQL_DB=XXXXXXX
      - MYSQL_USER=XXXXXXX
      - MYSQL_PASSWORD=XXXXXXX
      - SITE_NAME=cyicz123的博客
      - SITE_URL=https://blog.cyicz123.top
      - SECURE_DOMAINS=XXXXXXX
      - AUTHOR_EMAIL=cyicz123@outlook.com
      - QYWX_AM=XXXXXXX
      - DISABLE_REGION=false
    depends_on:
      - mysql


  mysql:
    image: mysql:5.7
    container_name: waline-db
    restart: always
    environment:
      - MYSQL_DATABASE=XXXXXXX
      - MYSQL_USER=XXXXXXX
      - MYSQL_PASSWORD=XXXXXXX
      - MYSQL_ROOT_PASSWORD=XXXXXXX
    volumes:
      - ./db:/var/lib/mysql
      - ./db.sql:/docker-entrypoint-initdb.d/db.sql
```
