### ISSUE TITLE
[Bug]: 独立部署Waline无法连接到Mysql数据库

### ISSUE THREAD

**Issue by kaolengmian7** [walinejs/waline#1496]
### 问题描述 | Describe the bug

采用独立部署的方式部署Waline 和 Mysql。经测试报错：
```
Error: Not initialized
    at request (/app/node_modules/leancloud-storage/dist/node/request.js:156:11)
    at AV.Query._createRequest (/app/node_modules/leancloud-storage/dist/node/query.js:388:14)
    at AV.Query.find (/app/node_modules/leancloud-storage/dist/node/query.js:417:26)
    at module.exports._select (/app/node_modules/@waline/vercel/src/service/storage/leancloud.js:114:33)
    at module.exports.select (/app/node_modules/@waline/vercel/src/service/storage/leancloud.js:131:24)
    at module.exports.postAction (/app/node_modules/@waline/vercel/src/controller/comment.js:501:50)
    at /app/node_modules/think-controller/index.js:55:32
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
```
判断原因是 Waline 无法连接到 Mysql。这里给出我的 docker-compose:
```
version: '3'
networks:
  myweb:
    driver: bridge

services:
  waline:
    container_name: waline
    image: lizheming/waline:latest
    restart: always
    ports:
      - 127.0.0.1:8360:8360
    volumes:
      - ~/app/data:/app/data
    environment:
      TZ: 'Asia/Shanghai'
      SITE_NAME: 'Your site name'
      SITE_URL: 'http://127.0.0.1:9097'
      AUTHOR_EMAIL: 'mail@example.com'
      MYSQL_DATABASE: waline
      MYSQL_USER: kaolengmian
      MYSQL_PASSWORD: 1234
    networks:
      - myweb

  mysql:
    container_name: app_mysql
    image: mysql:8.0
    environment:
      TZ: Asia/Shanghai
      RUNTIME_ENV: dev
      MYSQL_DATABASE: waline
      MYSQL_USER: kaolengmian
      MYSQL_PASSWORD: 1234
      MYSQL_ROOT_PASSWORD: 1234
    volumes:
      - ~/app/mysql/mydir:/mydir
      - ~/app/mysql/datadir:/var/lib/mysql
      - ~/app/mysql/conf/my.cnf:/etc/my.cnf
      # 数据库还原目录 可将需要还原的sql文件放在这里
      - ~/app/mysql/source:/docker-entrypoint-initdb.d
    restart: always
    user: mysql
    networks:
      - myweb
 ```
数据库情况一切正常：
```
haoyufei@Diablo app % docker exec -it app_mysql bash
bash-4.4$ mysql -u kaolengmian -p
Enter password:
Welcome to the MySQL monitor.  Commands end with ; or \g.
Your MySQL connection id is 10
Server version: 8.0.31 MySQL Community Server - GPL

Copyright (c) 2000, 2022, Oracle and/or its affiliates.

Oracle is a registered trademark of Oracle Corporation and/or its
affiliates. Other names may be trademarks of their respective
owners.

Type 'help;' or '\h' for help. Type '\c' to clear the current input statement.

mysql> use waline;
Reading table information for completion of table and column names
You can turn off this feature to get a quicker startup with -A

Database changed
mysql> show tables;
+------------------+
| Tables_in_waline |
+------------------+
| wl_Comment       |
| wl_Counter       |
| wl_Users         |
+------------------+
3 rows in set (0.01 sec)

mysql>
```

### 问题网站 | Website URL

localhost

### 服务部署在哪里？ | Where your waline deploy?

Docker

### 数据存储在哪里？| Where your comment data store?

MySQL
