### ISSUE TITLE
[Bug]:  一直请求https://127.0.0.1:8360/api/token?lang=zh-CN || [Bug]: Always request https://127.0.0.1:8360/api/token?lang=zh-CN

### ISSUE THREAD

**Issue by bboysoulcn** [walinejs/waline#1917]
### 问题描述 | Describe the bug

登录时候一直请求https://127.0.0.1:8360/api/token?lang=zh-CN导致不能登录 1.27.0没有这个问题，1.28.0就有了

### 问题网站 | Website URL

https://test.test.com

### 服务部署在哪里？ | Where your waline deploy?
docker

### 数据存储在哪里？| Where your comment data store?

mysql

---
### Description of the problem | Describe the bug

When logging in, I keep requesting https://127.0.0.1:8360/api/token?lang=zh-CN and cannot log in. 1.27.0 does not have this problem, but 1.28.0 does.

### Problem Website | Website URL

https://test.test.com

### Where is the service deployed? | Where your waline deploy?
docker

### Where is the data stored? | Where your comment data store?

mysql

**Comment by lizheming** [comment]
可以更新到 1.28.2 再看看哈，两个小版本修复了点问题。如果问题还在可以提供个地址我 check 下，我本地试了下是没问题的。

**Comment by bboysoulcn** [comment]
不行的，

```yaml
version: '3'

services:
  waline:
    container_name: waline
    image: lizheming/waline:1.28.2
    restart: always
    ports:
      - 8360:8360
    volumes:
      - ./data:/app/data
    environment:
      - "TZ=Asia/Shanghai"
      - "SQLITE_PATH=/app/data"
      - "JWT_TOKEN="
      - "SITE_NAME=blog"
      - "SITE_URL="
      - "SMTP_SERVICE="
      - "SMTP_USER=@163.com"
      - "SMTP_PASS="
      - "AUTHOR_EMAIL=@.com"
      - "SECURE_DOMAINS="
      - "AKISMET_KEY=false"
```
