### ISSUE TITLE
[Bug]: 邮箱无法发送，无法登录 || [Bug]: The mailbox cannot be sent and cannot be logged in

### ISSUE THREAD

**Issue by heStudio-Network** [walinejs/waline#1998]
### 问题描述 | Describe the bug

通过docker-compose部署，配置文件如下
```yaml
version: '3.8'
services:
  web:
    image: 'lizheming/waline'
    restart: always
    ports:
      - 127.0.0.1:8360:8360
    volumes:
      - ${PWD}/data:/app/data
    environment:
      AKISMET_KEY: "xxxxxxx"
      MYSQL_HOST: 'xxx.xxx.xxx.xxx'
      MYSQL_PORT: '3306'
      MYSQL_DB: 'comment'
      MYSQL_USER: 'comment'
      MYSQL_PASSWORD: 'xxxxxxx'
      MYSQL_SSL: true
      SMTP_HOST: 'smtp.mxhichina.com'
      SMTP_PORT: '465'
      SMTP_USER: 'hestudio@hestudio.net'
      SMTP_PASS: 'xxxxxxx'
      SMTP_SECURE: false
      SENDER_NAME: 'heStudio'
      AUTHOR_EMAIL: 'zihengdie@hestudio.net'
      SITE_NAME: 'heStudio'
      SITE_URL: 'https://www.hestudio.net'
      LOGIN: 'force'
      OAUTH_URL: "http://auth.hestudio.net"
```

邮箱在其他工具通过相同配置测试正常，数据库测试正常，评论正常显示，但
![Screenshot_2023-06-03-08-08-57-81_fab32b241c9ab51b0e057c943b753947](https://github.com/walinejs/waline/assets/119711513/9934fa4e-763f-4aed-a503-0c01b61d2a49)
无法登录，也无法找回密码

https://github.com/walinejs/waline/assets/119711513/11b6f696-8b12-489d-abf9-621aa14f2f88

![Screenshot_2023-06-03-08-36-25-18_fab32b241c9ab51b0e057c943b753947](https://github.com/walinejs/waline/assets/119711513/9946c1d3-8497-4670-b2c1-3fbeb53d74f2)

### 问题网站 | Website URL

https://www.hestudio.net/talking

### 服务部署在哪里？ | Where your waline deploy?

Docker

### 数据存储在哪里？| Where your comment data store?

MySQL

---
### Description of the problem | Describe the bug

Deployed through docker-compose, the configuration file is as follows
```yaml
version: '3.8'
services:
  web:
    image: 'lizheming/waline'
    restart: always
    ports:
      - 127.0.0.1:8360:8360
    volumes:
      - ${PWD}/data:/app/data
    environment:
      AKISMET_KEY: "xxxxxxx"
      MYSQL_HOST: 'xxx.xxx.xxx.xxx'
      MYSQL_PORT: '3306'
      MYSQL_DB: 'comment'
      MYSQL_USER: 'comment'
      MYSQL_PASSWORD: 'xxxxxxx'
      MYSQL_SSL: true
      SMTP_HOST: 'smtp.mxhichina.com'
      SMTP_PORT: '465'
      SMTP_USER: 'hestudio@hestudio.net'
      SMTP_PASS: 'xxxxxxx'
      SMTP_SECURE: false
      SENDER_NAME: 'heStudio'
      AUTHOR_EMAIL: 'zihengdie@hestudio.net'
      SITE_NAME: 'heStudio'
      SITE_URL: 'https://www.hestudio.net'
      LOGIN: 'force'
      OAUTH_URL: "http://auth.hestudio.net"
```

The mailbox is tested normally through the same configuration in other tools, the database test is normal, and the comments are displayed normally, but
![Screenshot_2023-06-03-08-08-57-81_fab32b241c9ab51b0e057c943b753947](https://github.com/walinejs/waline/assets/119711513/9934fa4e-763f-4aed-a503-0c01b61d 2a49)
Can't log in and can't retrieve password

https://github.com/walinejs/waline/assets/119711513/11b6f696-8b12-489d-abf9-621aa14f2f88

![Screenshot_2023-06-03-08-36-25-18_fab32b241c9ab51b0e057c943b753947](https://github.com/walinejs/waline/assets/119711513/9946c1d3-8497-4670-b2c1-3fbeb53 d74f2)

### Problem Website | Website URL

https://www.hestudio.net/talking

### Where is the service deployed? | Where your waline deploy?

Docker

### Where is the data stored? | Where your comment data store?

MySQL
