### ISSUE TITLE
[Bug]: docker-compose配置安全域名不生效 || [Bug]: docker-compose configured secure domain name does not take effect

### ISSUE THREAD

**Issue by kdyzm** [walinejs/waline#2294]
### 问题描述 | Describe the bug

``` yaml
version: '3'

services:
  waline:
    container_name: waline
    image: lizheming/waline:latest
    restart: always
    ports:
      - 8360:8360
    volumes:
      - ${PWD}/data:/app/data
    environment:
      ......
      SECURE_DOMAINS: 'blog.kdyzm.cn'
```

按道理配置了这个安全域名，在localhost访问应该会失败吧，但是仍然能访问

### 问题网站 | Website URL

http://localhost

### 服务部署在哪里？ | Where your waline deploy?

Self Host

### 数据存储在哪里？| Where your comment data store?

MySQL

---
### Problem description | Describe the bug

```yaml
version: '3'

services:
  waline:
    container_name:waline
    image: lizheming/waline:latest
    restart: always
    ports:
      - 8360:8360
    volumes:
      - ${PWD}/data:/app/data
    environment:
      ...
      SECURE_DOMAINS: 'blog.kdyzm.cn'
```

It stands to reason that after configuring this secure domain name, accessing it on localhost should fail, but you can still access it.

### Question Website | Website URL

http://localhost

### Where is the service deployed? | Where your waline deploy?

Self Host

### Where is the data stored? | Where your comment data store?

MySQL
