### ISSUE TITLE
[Bug]: Got SyntaxError & ReferenceError when Importing waline.js v3 by CDN | 通过CDN导入waline.js v3时得到语法错误与引用错误

### ISSUE THREAD

**Issue by Trichiurus-lepturus** [walinejs/waline#2483]
### 问题描述 | Describe the bug

To import waline I use `@waline/hexo-next` npm package, which imports waline via CDN.
I used to use waline v2 and was without the errors below.
Now I try to update to v3, changed in _config.next.yml like:
```yaml
waline:
  # libUrl: https://unpkg.com/@waline/client@v2/dist/waline.js
  libUrl: https://unpkg.com/@waline/client@v3/dist/waline.js
  # cssUrl: https://unpkg.com/@waline/client@v2/dist/waline.css
  cssUrl: https://unpkg.com/@waline/client@v3/dist/waline.css
```
(The config before are marked as a comment.)
Deploy the website, visit and waline is gone. Nothing between `<div class="comments animated fadeIn" id="waline">`and`</div>`.
Use 'Inspect' to check and in Console tab shows these errors:
```
Uncaught SyntaxError: export declarations may only appear at top level of a module [waline.js:71:20998](https://unpkg.com/@waline/client@v3/dist/waline.js)
Uncaught (in promise) ReferenceError: Waline is not defined
    <anonymous> https://daiyu.host/2024/04/16/hello-world/:392
```
The statement near the position indicated by SyntaxError (in waline.js, line 71, col 20998) is like this (formatted by WebStorm):
``` JavaScript
export
{
    zd as RecentComments,
    jd as UserList,
    Ar as addComment,
    no as commentCount,
    An as defaultLocales,
    Ir as deleteComment,
    Lr as fetchCommentCount,
    Ci as getArticleCounter,
    Sr as getComment,
    Or as getPageview,
    jr as getRecentComment,
    Pr as getUserList,
    Od as init,
    Mr as login,
    mo as pageviewCount,
    Sn as updateArticleCounter,
    Zt as updateComment,
    zr as updatePageview,
    po as version
};
```
It seems that this is exactly the statement that throws the SyntaxError.
However I have no clue to fix these errors after reading the docs carefully.
Both Firefox (version 125.0) and Chromium (version 122.0) throws these two errors.

---

我使用@waline/hexo-next包，此包通过CDN导入waline。
我之前使用waline v2，没有遇到下文说的error。
尝试更新到waline v3，我对_config.next.yml做出了以下改变：
```yaml
waline:
  # libUrl: https://unpkg.com/@waline/client@v2/dist/waline.js
  libUrl: https://unpkg.com/@waline/client@v3/dist/waline.js
  # cssUrl: https://unpkg.com/@waline/client@v2/dist/waline.css
  cssUrl: https://unpkg.com/@waline/client@v3/dist/waline.css
```
（之前的配置以注释表示）
部署网站并访问后，发现waline评论区消失，`<div class="comments animated fadeIn" id="waline"><div>`之间没有内容。
用开发者工具查看，在Console选项卡下发现了两个error：
```
Uncaught SyntaxError: export declarations may only appear at top level of a module [waline.js:71:20998](https://unpkg.com/@waline/client@v3/dist/waline.js)
Uncaught (in promise) ReferenceError: Waline is not defined
    <anonymous> https://daiyu.host/2024/04/16/hello-world/:392
```
其中SyntaxError显示的位置附近（waline.js，71行20998列）的代码如下（使用Webstorm格式化过）：
``` JavaScript
export
{
    zd as RecentComments,
    jd as UserList,
    Ar as addComment,
    no as commentCount,
    An as defaultLocales,
    Ir as deleteComment,
    Lr as fetchCommentCount,
    Ci as getArticleCounter,
    Sr as getComment,
    Or as getPageview,
    jr as getRecentComment,
    Pr as getUserList,
    Od as init,
    Mr as login,
    mo as pageviewCount,
    Sn as updateArticleCounter,
    Zt as updateComment,
    zr as updatePageview,
    po as version
};
```
报错的语句应当就是上面的这一句，但我仔细阅读过文档后，也没能找到修复以上错误的线索。
Firefox (版本125.0）和Chromium（版本122.0）的报错是吻合的。

### 问题网站 | Website URL

https://daiyu.host/2024/04/16/hello-world/

### 服务部署在哪里？ | Where your waline deploy?

Vercel (Default)

### 数据存储在哪里？| Where your comment data store?

LeanCloud(https://leancloud.app)
