### ISSUE TITLE
[Feature Request] 希望能够添加大表情功能

### ISSUE THREAD

**Issue by kottory** [walinejs/waline#438]
以 Bilibili 为例。B站会为小表情（默认小电视小黄豆）等添加一个 `emoji-small` 的类，以区分与大表情的不同显示。
比如大表情：
```css
<a class="emoji-list emoji-text emoji-pic" ...></a>
```
小表情
```
<a class="class="emoji-list emoji-text emoji-pic emoji-small" ...></a>
```
我在具体部署的过程中，因为不考虑使用小表情，因此可以直接在 CSS 中描述：
```css
.v[data-class=v] .vcontent .vemoji {
    vertical-align: bottom !important;
    width: 3em !important;
}
```
但考虑到会有大小表情混用的需求，纯靠样式就没法区分了。作者是否有计划实现类似功能呢？这可能需要在 `info.json` 中的添加相关选项。
