### ISSUE TITLE
[BUG] 无法注册

### ISSUE THREAD

**Issue by yiyungent** [walinejs/waline#447]
**问题描述 | Describe the bug**

无法注册，使用 `Docker Compose`

```bash
docker-compose up -d
```

```yml
version: '3'

services:
  waline:
    container_name: waline
    image: lizheming/waline:latest
    restart: always
    ports:
      - 8360:8360
    volumes:
      - ${PWD}/data:/app/data
    environment:
      TZ: 'Asia/Shanghai'
      SQLITE_PATH: '/app/data'
      JWT_TOKEN: 'ndqdnwjqe'
      SITE_NAME: 'Waline'
      SITE_URL: 'https://waline.moeci.com'
      SECURE_DOMAINS: 'moeci.com'
      AUTHOR_EMAIL: 'i@moeci.com'
      GITHUB_ID: 'xxxxx'
      GITHUB_SECRET: 'xxxx'
```

![image](https://user-images.githubusercontent.com/16939388/128190141-d0dbe0a5-5dfa-4ec6-b991-a067d12f3e1e.png)

![image](https://user-images.githubusercontent.com/16939388/128190227-2810749a-f7ab-4e83-8ee7-7d0579bdb270.png)

**问题网站 | Website URL**

- https://waline.moeci.com/ui/register

**部署方式 | Deploy Type**

- 服务部署在哪里？ | Where your waline deploy?
  - [ ] Vercel
  - [ ] CloudBase
  - [x] Docker
  - [ ] VPS, Virtual Host
  - [ ] Other
- 数据存储在哪里？| Where your comment data store?
  - [ ] LeanCloud(https://leancloud.app)
  - [ ] LeanCloud(https://leancloud.cn)
  - [ ] CloudBase
  - [ ] MongoDB
  - [ ] MySQL
  - [x] SQLite
  - [ ] PostgreSQL
  - [ ] GitHub
