### ISSUE TITLE
[BUG] 使用 @waline/hexo-next 后 Template render error

### ISSUE THREAD

**Issue by yiyungent** [walinejs/waline#448]
**问题描述 | Describe the bug**

> 使用的新配置方式，请自行看 `Hexo`, `Next`文档,  `_config.next.yml`
```yml
# Waline
# For more information: https://waline.js.org, https://github.com/lizheming/waline
# https://www.npmjs.com/package/@waline/hexo-next
waline:
  enable: true
  serverURL: https://waline.moeci.com # Waline server address url
  placeholder: Just go go # Comment box placeholder
  avatar: mm # Gravatar style
  meta: [nick, mail, link] # Custom comment header
  pageSize: 10 # Pagination size
  lang: # Language, available values: en, zh-cn
  # Warning: Do not enable both `waline.visitor` and `leancloud_visitors`.
  visitor: false # Article reading statistic
  comment_count: true # If false, comment count will only be displayed in post page, not in home page
  requiredFields: [] # Set required fields: [nick] | [nick, mail]
  libUrl: # Set custom library cdn url
```

```bash
hexo server
```

再访问 `http://localhost:4000` 后发现，使用此插件后生成出错了，导致页面全部空白

![image](https://user-images.githubusercontent.com/16939388/128193006-986a04b6-0611-40df-a098-540142faed33.png)

![image](https://user-images.githubusercontent.com/16939388/128192027-8b580ca1-2e41-41e3-b263-a1a9fe8ce4c7.png)

```
Template render error: (F:\Com\me\Repos\yiyungent.github.io\node_modules\hexo-theme-next\layout\inject\bodyEnd\waline.njk) [Line 5, Column 15]
  Error: Unable to call `next_data`, which is undefined or falsey
    at Object._prettifyError (F:\Com\me\Repos\yiyungent.github.io\node_modules\nunjucks\src\lib.js:36:11)
    at F:\Com\me\Repos\yiyungent.github.io\node_modules\nunjucks\src\environment.js:561:19
    at Template.root [as rootRenderFunc] (eval at _compile (F:\Com\me\Repos\yiyungent.github.io\node_modules\nunjucks\src\environment.js:631:18), <anonymous>:43:3)
    at Template.render (F:\Com\me\Repos\yiyungent.github.io\node_modules\nunjucks\src\environment.js:550:10)
    at F:\Com\me\Repos\yiyungent.github.io\node_modules\hexo\lib\plugins\renderer\nunjucks.js:67:37
    at _View._compiled (F:\Com\me\Repos\yiyungent.github.io\node_modules\hexo\lib\theme\view.js:136:50)
    at _View.render (F:\Com\me\Repos\yiyungent.github.io\node_modules\hexo\lib\theme\view.js:39:17)
    at F:\Com\me\Repos\yiyungent.github.io\node_modules\hexo\lib\hexo\index.js:64:21
    at tryCatcher (F:\Com\me\Repos\yiyungent.github.io\node_modules\bluebird\js\release\util.js:16:23)
    at F:\Com\me\Repos\yiyungent.github.io\node_modules\bluebird\js\release\method.js:15:34
    at RouteStream._read (F:\Com\me\Repos\yiyungent.github.io\node_modules\hexo\lib\hexo\router.js:47:5)
    at RouteStream.Readable.read (_stream_readable.js:459:10)
    at resume_ (_stream_readable.js:948:12)
    at processTicksAndRejections (internal/process/task_queues.js:84:21)
```

> 报错信息太多了，这里只截取部分

> 只要再把 `enable: false`，`hexo server` 页面就正常了，也不会报错

**问题网站 | Website URL**

- https://moeci.com
  - ( 安装了 @waline/hexo-next 的 Hexo 博客 )
- https://waline.moeci.com
  - ( Waline run on Docker Compose )
- https://github.com/yiyungent/yiyungent.github.io
  - (安装了 @waline/hexo-next 的 Hexo仓库 ,暂时 public，解决问题后，我会 private )

**部署方式 | Deploy Type**

- 服务部署在哪里？ | Where your waline deploy?
  - [ ] Vercel
  - [ ] CloudBase
  - [x] Docker
  - [ ] VPS, Virtual Host
  - [ ] Other
- 数据存储在哪里？| Where your comment data store?
  - [ ] LeanCloud(https://leancloud.app)
  - [ ] LeanCloud(https://leancloud.cn)
  - [ ] CloudBase
  - [ ] MongoDB
  - [ ] MySQL
  - [x] SQLite
  - [ ] PostgreSQL
  - [ ] GitHub
