### ISSUE TITLE
[BUG] wordLimit不能正常在右下角显示。

### ISSUE THREAD

**Issue by zj713300** [walinejs/waline#490]
**问题描述 | Describe the bug**

使用@waline/hexo-next

`_config.next.yml`：
```yml
waline:
  enable: true
  serverURL: 'https://waline.woruo.online'
  placeholder: '来和若若聊天吧~可以选择匿名哦！'
  avatar: 'mm'
  meta: ['nick', 'mail']
  pageSize: 10
  lang: 'zh-CN'
  login: 'disable'
  visitor: true
  wordLimit: 1024
  avatarCDN: 'https://gravatar.loli.net/avatar/'
  uploadImage: false
  copyright: false
  comment_count: true
  requiredMeta: []
  libUrl: 'https://cdn.jsdelivr.net/npm/@waline/client@1.3.3/dist/Waline.min.js'
  emoji: ['https://cdn.jsdelivr.net/gh/walinejs/emojis@latest/qq']
```

`docker-compose.yml`：
```yml
environment:
  TZ: 'Asia/Shanghai'
  SITE_NAME: '沃若の笔记本'
  DISABLE_USERAGENT: 'true'
  SITE_URL: 'https://blog.woruo.online'
  IPQPS: 1
  SECURE_DOMAINS: 'blog.woruo.online, waline.woruo.online'
  AKISMET_KEY: 'false'
  AUTHOR_EMAIL: 'woruo@woruo.online'
  SMTP_HOST: 'smtp.qq.com'
  SMTP_PORT: 465
  SMTP_USER: '脱敏处理'
  SMTP_PASS: '脱敏处理'
  SENDER_NAME: '沃若'
  SENDER_EMAIL: '脱敏处理'
  MAIL_SUBJECT: '你在{{site.name}}的评论有新回复啦'
  MAIL_TEMPLATE: "你在{{site.name}}的评论：<br>{{parent.comment}}<br>收到了来自{{self.nick}}的新回复：{{self.comment}}<br>仅供预览，查看完整内容：{{site.postUrl}}"
  MAIL_SUBJECT_ADMIN: '来自{{self.nick}}的新评论'
  MAIL_TEMPLATE_ADMIN: "{{self.nick}}评论道：<br>{{self.comment}}<br>仅供预览，查看完整内容：{{site.postUrl}}"
  MYSQL_HOST: '脱敏处理'
  MYSQL_DB: '脱敏处理'
  MYSQL_USER: '脱敏处理'
  MYSQL_PASSWORD: '脱敏处理'
```

![image](https://user-images.githubusercontent.com/23548024/130591816-59bdc29b-a90f-4c61-9b67-03072e9b4d65.png)
![image](https://user-images.githubusercontent.com/23548024/130591844-fcfb1638-c564-4ca3-8ae6-368eb65def6e.png)

**问题网站 | Website URL**

近期可能会下线：`blog.woruo.online`

**部署方式 | Deploy Type**

- 服务部署在哪里？ | Where your waline deploy?
  - [ ] Vercel
  - [ ] CloudBase
  - [x] Docker
  - [ ] VPS, Virtual Host
  - [ ] Other
- 数据存储在哪里？| Where your comment data store?
  - [ ] LeanCloud(https://leancloud.app)
  - [ ] LeanCloud(https://leancloud.cn)
  - [ ] CloudBase
  - [ ] MongoDB
  - [x] MySQL
  - [ ] SQLite
  - [ ] PostgreSQL
  - [ ] GitHub
